# Generated by Django 5.1.2 on 2024-10-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdataamz',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='salesdataamz',
            name='shipment_date',
            field=models.DateTimeField(),
        ),
    ]
