# Generated by Django 5.1.2 on 2024-10-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_salesdataamz_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdataamz',
            old_name='sgst_state',
            new_name='sgst_rate',
        ),
    ]
