# Generated by Django 5.1.2 on 2024-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_sgst_state_salesdataamz_sgst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdataamz',
            name='credit_note_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salesdataamz',
            name='invoice_date',
            field=models.DateTimeField(),
        ),
    ]
