# Generated by Django 5.1.2 on 2024-10-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_salesdataamz_credit_note_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdataamz',
            name='credit_note_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdataamz',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdataamz',
            name='shipment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
