# Generated by Django 5.1.2 on 2024-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_salesdataamz_credit_note_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdataamz',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
