# Generated by Django 5.1.2 on 2024-10-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_salesdataamz_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdataamz',
            old_name='warehouse',
            new_name='warehouse_id',
        ),
    ]
