# Generated by Django 5.1.2 on 2024-10-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_warehouse_salesdataamz_warehouse_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesDataAMZ',
            new_name='First_step_SalesData_AMZ',
        ),
        migrations.AlterModelTable(
            name='first_step_salesdata_amz',
            table='First_step_SalesData_AMZ',
        ),
    ]
