# Generated by Django 5.1.2 on 2024-10-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_salesdataamz_first_step_salesdata_amz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_SalesData_FK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_gstin', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('order_item_id', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=500)),
                ('fsn', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('event_sub_type', models.CharField(max_length=255)),
                ('order_type', models.CharField(max_length=255)),
                ('fulfilment_type', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_approval_date', models.DateTimeField(blank=True, null=True)),
                ('item_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_shipped_from_state', models.CharField(max_length=255)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('price_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_offer_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_of_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luxury_cess_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luxury_cess_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs_igst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs_igst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs_gst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs_gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs_sgst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcs_sgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tcs_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_invoice_id', models.CharField(max_length=255)),
                ('buyer_invoice_date', models.DateTimeField(blank=True, null=True)),
                ('buyer_invoive_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_billing_pincode', models.CharField(max_length=255)),
                ('customer_billing_state', models.CharField(max_length=255)),
                ('customer_delivery_pincode', models.CharField(max_length=255)),
                ('customer_delivery_state', models.CharField(max_length=255)),
                ('usual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_shopsy_order', models.CharField(max_length=255)),
                ('tds_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
