# Generated by Django 5.1.2 on 2024-10-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_first_step_salesdata_fk'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='first_step_salesdata_fk',
            table='First_step_SalesData_FK',
        ),
    ]
