# Generated by Django 5.1.2 on 2024-10-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_first_step_salesdata_fk_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_step_salesdata_fk',
            old_name='luxury_cess_tax',
            new_name='luxury_cess_rate',
        ),
        migrations.RenameField(
            model_name='first_step_salesdata_fk',
            old_name='tcs_gst_amount',
            new_name='tcs_cgst_amount',
        ),
        migrations.RenameField(
            model_name='first_step_salesdata_fk',
            old_name='tcs_gst_rate',
            new_name='tcs_cgst_rate',
        ),
        migrations.RemoveField(
            model_name='first_step_salesdata_fk',
            name='usual_price',
        ),
    ]
