# Generated by Django 5.1.2 on 2024-10-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_luxury_cess_tax_first_step_salesdata_fk_luxury_cess_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_step_salesdata_fk',
            name='usual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
