# Generated by Django 5.1.2 on 2024-10-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_first_step_salesdata_fk_usual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_salesdata_fk',
            name='seller_gstin',
            field=models.CharField(max_length=500),
        ),
    ]
