# Generated by Django 5.1.2 on 2024-10-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_first_step_salesdata_fk_seller_gstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_step_salesdata_fk',
            name='usual_price',
        ),
    ]
