# Generated by Django 5.1.2 on 2024-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_first_step_salesdata_fk_usual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_step_salesdata_fk',
            name='usual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
