# Generated by Django 5.1.2 on 2024-11-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_first_step_cogs_vertical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_InvoiceData_FK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255)),
                ('order_item_id', models.CharField(max_length=255)),
                ('recall_id', models.CharField(max_length=255)),
                ('warehouse_state_code', models.CharField(max_length=255)),
                ('fee_name', models.CharField(max_length=255)),
                ('total_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_wavier_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'First_step_invoice_FK',
            },
        ),
    ]
