# Generated by Django 5.1.2 on 2024-11-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_first_step_invoicedata_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_step_invoicedata_fk',
            old_name='fee_wavier_amount',
            new_name='fee_waiver_amount',
        ),
    ]
