# Generated by Django 5.1.2 on 2024-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_fee_wavier_amount_first_step_invoicedata_fk_fee_waiver_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_AdsData_FK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=255)),
                ('campaign_name', models.CharField(max_length=255)),
                ('ad_group_id', models.CharField(max_length=255)),
                ('ad_group_name', models.CharField(max_length=255)),
                ('placement_type', models.CharField(max_length=255)),
                ('views', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clicks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cvr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ad_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold_direct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold_indirect', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direct_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indirect_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roi_direct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roi_indirect', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'First_step_Ad_spend_FK',
            },
        ),
    ]
