# Generated by Django 5.1.2 on 2024-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_first_step_adsdata_fk_average_cpc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_Master_SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=500)),
                ('ean', models.CharField(max_length=200)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fk_platform_sku', models.CharField(max_length=300)),
                ('fk_fsn', models.CharField(max_length=255)),
                ('amazon_platform_sku', models.CharField(max_length=255)),
                ('amazon_asin', models.CharField(max_length=255)),
                ('first_cry_platform_sku', models.CharField(max_length=255)),
                ('first_cry_product_id', models.CharField(max_length=255)),
                ('myntra_platformsku', models.CharField(max_length=255)),
                ('myntra_product_id', models.CharField(max_length=255)),
                ('jiomart_platform_sku', models.CharField(max_length=255)),
                ('jiomart_product_id', models.CharField(max_length=255)),
                ('meesho_platform_sku', models.CharField(max_length=255)),
                ('meesho_product_id', models.CharField(max_length=255)),
                ('pharmeasy_platform_sku', models.CharField(max_length=255)),
                ('pharmeasy_product_id', models.CharField(max_length=255)),
                ('rk_world_platform_sku', models.CharField(max_length=255)),
                ('rk_world_product_id', models.CharField(max_length=255)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hsn', models.CharField(max_length=255)),
                ('cogs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vertical', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'First_step_Master_sku',
            },
        ),
    ]
