# Generated by Django 5.1.2 on 2024-11-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_first_step_master_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_step_master_sku',
            name='product_vertical',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='vertical',
            field=models.CharField(max_length=400),
        ),
    ]
