# Generated by Django 5.1.2 on 2024-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_first_step_master_sku_product_vertical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
