# Generated by Django 5.1.2 on 2024-11-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_first_step_master_sku_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_step_master_sku',
            name='sku',
        ),
    ]
