# Generated by Django 5.1.2 on 2024-11-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_first_step_master_sku_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='first_step_master_sku',
            name='vertical',
        ),
        migrations.AddField(
            model_name='first_step_master_sku',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
