# Generated by Django 5.1.2 on 2024-11-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_first_step_master_sku_vertical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='amazon_asin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='amazon_platform_sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='breadth',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='cogs',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='ean',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='first_cry_platform_sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='first_cry_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='fk_fsn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='fk_platform_sku',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='gst',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='height',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='hsn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='jiomart_platform_sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='jiomart_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='length',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='meesho_platform_sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='meesho_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='mrp',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='myntra_platformsku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='myntra_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='pharmeasy_platform_sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='pharmeasy_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='product_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='rk_world_platform_sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='rk_world_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_master_sku',
            name='weight',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
