# Generated by Django 5.1.2 on 2024-11-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_uploadedfiletracker'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfiletracker',
            table='list_of_files_uploaded',
        ),
    ]
