# Generated by Django 5.1.3 on 2024-12-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_jr_sr_adsdata_fk_jr_sr_invoicedata_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jr_Sr_cogs_master_sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('pack_size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('check_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100)),
                ('fsn', models.CharField(max_length=100)),
                ('lid', models.CharField(max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('settlement_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cogs', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Jr_Sr_cogs_master_sku',
            },
        ),
    ]
