# Generated by Django 5.1.3 on 2024-12-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_jr_sr_cogs_master_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='pack_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='settlement_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
