# Generated by Django 5.1.3 on 2024-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_jr_sr_cogs_master_sku_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='settlement_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
