# Generated by Django 5.1.3 on 2024-12-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_jr_sr_cogs_master_sku_settlement_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='total_cogs',
            field=models.CharField(max_length=100),
        ),
    ]
