# Generated by Django 5.1.3 on 2024-12-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_jr_sr_cogs_master_sku_total_cogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='jr_sr_cogs_master_sku',
            name='pack_size',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
