# Generated by Django 5.1.3 on 2024-12-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_jr_sr_cogs_master_sku_mrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jr_Sr_AdsData_FK_MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=150)),
                ('campaign_name', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('ad_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('views', models.DecimalField(decimal_places=2, max_digits=9)),
                ('clicks', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_converted_units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Jr_Sr_AdsData_FK_MP',
            },
        ),
        migrations.DeleteModel(
            name='Jr_Sr_AdsData_FK',
        ),
    ]
