# Generated by Django 5.1.3 on 2024-12-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_jr_sr_adsdata_fk_mp_delete_jr_sr_adsdata_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_step_cogs_vertical',
            old_name='cogs_excl_gst',
            new_name='cogs',
        ),
        migrations.RenameField(
            model_name='jr_sr_cogs_master_sku',
            old_name='total_cogs',
            new_name='cogs',
        ),
        migrations.RenameField(
            model_name='jr_sr_cogs_master_sku',
            old_name='title',
            new_name='product_title',
        ),
        migrations.RenameField(
            model_name='jr_sr_cogs_master_sku',
            old_name='vertical',
            new_name='product_vertical',
        ),
    ]
