# Generated by Django 5.1.3 on 2024-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_rename_cogs_excl_gst_first_step_cogs_vertical_cogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jr_Sr_cogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=300)),
                ('sku', models.CharField(max_length=100)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Jr_Sr_cogs',
            },
        ),
    ]
