# Generated by Django 5.1.3 on 2024-12-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_jr_sr_cogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jr_sr_adsdata_fk_mp',
            old_name='ad_spend',
            new_name='ads_spend',
        ),
    ]
