# Generated by Django 5.1.3 on 2024-12-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_rename_ad_spend_jr_sr_adsdata_fk_mp_ads_spend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jr_sr_adsdata_fk_mp',
            old_name='ads_spend',
            new_name='ad_spend',
        ),
    ]
