# Generated by Django 5.1.3 on 2025-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_rename_ads_spend_jr_sr_adsdata_fk_mp_ad_spend'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_CODBFeesData_AMZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_store', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('parent_asin', models.CharField(max_length=100, null=True)),
                ('asin', models.CharField(max_length=100, null=True)),
                ('fnsku', models.CharField(blank=True, max_length=100, null=True)),
                ('msku', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_code', models.CharField(max_length=50, null=True)),
                ('average_sales_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('units_returned', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_units_sold', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fba_weight_handling_fee_per_unit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fba_weight_handling_fee_quantity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fba_weight_handling_fee_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fixed_closing_fee_per_unit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fixed_closing_fee_quantity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fixed_closing_fee_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('referral_fee_per_unit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('referral_fee_quantity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('referral_fee_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('refund_commission_fee_per_unit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('refund_commission_fee_quantity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('refund_commission_fee_total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='First_step_SP_Ads_AMZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('portfolio_name', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('campaign_name', models.CharField(blank=True, max_length=100)),
                ('ad_group_name', models.CharField(blank=True, max_length=100)),
                ('targeting', models.CharField(blank=True, max_length=100)),
                ('match_type', models.CharField(blank=True, max_length=100)),
                ('impressions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('top_of_search_impression_share', models.DecimalField(decimal_places=5, max_digits=5)),
                ('clicks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ctr', models.DecimalField(decimal_places=5, max_digits=5)),
                ('cpc', models.DecimalField(decimal_places=5, max_digits=5)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_advertising_cost_of_sales', models.DecimalField(decimal_places=5, max_digits=5)),
                ('total_return_on_advertising_spend', models.DecimalField(decimal_places=5, max_digits=5)),
                ('day_14_total_sales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day_14_total_orders', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day_14_total_units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('day_14_conversion_rate', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
