# Generated by Django 5.1.3 on 2025-01-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_first_step_codbfeesdata_amz_first_step_sp_ads_amz'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_SB_Ads_AMZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('portfolio_name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('campaign_name', models.CharField(max_length=250)),
                ('cost_type', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('impressions', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clicks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ctr', models.DecimalField(decimal_places=4, max_digits=5)),
                ('cpc', models.DecimalField(decimal_places=4, max_digits=5)),
                ('spend', models.DecimalField(decimal_places=3, max_digits=10)),
                ('day_14_conversion_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('viewable_impressions', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_per_1000_viewable_impressions', models.DecimalField(decimal_places=5, max_digits=10)),
                ('view_through_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('click_through_rate_for_views', models.DecimalField(decimal_places=4, max_digits=10)),
                ('video_midpoint_views', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_third_quartile_views', models.DecimalField(decimal_places=4, max_digits=10)),
                ('video_complete_views', models.DecimalField(decimal_places=4, max_digits=10)),
                ('video_unmutes', models.DecimalField(decimal_places=4, max_digits=10)),
                ('seconds_5_views', models.DecimalField(decimal_places=4, max_digits=10)),
                ('seconds_5_view_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_branded_searches', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_detail_page_views', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_new_to_brand_orders', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_percent_of_orders_new_to_brand', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_new_to_brand_sales', models.DecimalField(decimal_places=5, max_digits=10)),
                ('day_14_percent_of_sales_new_to_brand', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_new_to_brand_units', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_percent_of_units_new_to_brand', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_new_to_brand_order_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_advertising_cost_of_sales', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_return_on_advertising_spend', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_total_sales', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_total_orders', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_total_units', models.DecimalField(decimal_places=4, max_digits=10)),
                ('new_to_brand_detail_page_views', models.DecimalField(decimal_places=4, max_digits=10)),
                ('new_to_brand_detail_page_view_click_through_conversions', models.DecimalField(decimal_places=4, max_digits=10)),
                ('new_to_brand_detail_page_view_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_cost_per_new_to_brand_detail_page_view', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_atc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_atc_clicks', models.DecimalField(decimal_places=4, max_digits=10)),
                ('day_14_atcr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_cost_per_add_to_cart', models.DecimalField(decimal_places=4, max_digits=10)),
                ('branded_searches_click_through_conversions', models.DecimalField(decimal_places=4, max_digits=10)),
                ('branded_searches_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_cost_per_branded_search', models.DecimalField(decimal_places=4, max_digits=10)),
                ('long_term_sales', models.DecimalField(decimal_places=4, max_digits=10)),
                ('long_term_roas', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
