# Generated by Django 5.1.3 on 2025-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_first_step_sb_ads_amz'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_SD_Ads_AMZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('portfolio_name', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=25, null=True)),
                ('campaign_name', models.CharField(max_length=100, null=True)),
                ('cost_type', models.CharField(max_length=100, null=True)),
                ('ad_group_name', models.CharField(max_length=100, null=True)),
                ('targeting', models.CharField(max_length=100, null=True)),
                ('bid_optimization', models.CharField(max_length=100, null=True)),
                ('impressions', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('viewable_impressions', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('clicks', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ctr', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('day_14_detail_page_views', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('cost_per_1000_viewable_impressions', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('total_advertising_cost_of_sales', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('total_return_on_advertising_spend', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('day_14_total_orders', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('day_14_total_units', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('day_14_total_sales', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('day_14_new_to_brand_orders', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('day_14_new_to_brand_sales', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('day_14_new_to_brand_units', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('total_advertising_cost_of_sales_clicks', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_return_on_advertising_spend_click', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('day_14_total_orders_click', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('day_14_total_units_click', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('day_14_total_sales_click', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('day_14_new_to_brand_orders_click', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('day_14_new_to_brand_sales_click', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('day_14_new_to_brand_units_click', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'First_step_SD_Ads_AMZ',
            },
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='branded_searches_click_through_conversions',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='branded_searches_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='campaign_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='click_through_rate_for_views',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='clicks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='cost_per_1000_viewable_impressions',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='cost_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='cpc',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='ctr',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_atc',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_atc_clicks',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_atcr',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_branded_searches',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_conversion_rate',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_detail_page_views',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_new_to_brand_order_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_new_to_brand_orders',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_new_to_brand_sales',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_new_to_brand_units',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_percent_of_orders_new_to_brand',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_percent_of_sales_new_to_brand',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_percent_of_units_new_to_brand',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_total_orders',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_total_sales',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_total_units',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='effective_cost_per_add_to_cart',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='effective_cost_per_branded_search',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='effective_cost_per_new_to_brand_detail_page_view',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='impressions',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='long_term_roas',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='long_term_sales',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='new_to_brand_detail_page_view_click_through_conversions',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='new_to_brand_detail_page_view_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='new_to_brand_detail_page_views',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='portfolio_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='seconds_5_view_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='seconds_5_views',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='spend',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='total_advertising_cost_of_sales',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='total_return_on_advertising_spend',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='video_complete_views',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='video_midpoint_views',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='video_third_quartile_views',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='video_unmutes',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='view_through_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='viewable_impressions',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='clicks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='cpc',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='ctr',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_conversion_rate',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_total_orders',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_total_units',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='impressions',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='spend',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='top_of_search_impression_share',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='total_advertising_cost_of_sales',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='total_return_on_advertising_spend',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
    ]
