# Generated by Django 5.1.3 on 2025-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_first_step_sd_ads_amz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_step_sb_ads_amz',
            name='day_14_total_orders_clicks',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='first_step_sb_ads_amz',
            name='day_14_total_sales_clicks',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='first_step_sb_ads_amz',
            name='day_14_total_units_clicks',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='first_step_sb_ads_amz',
            name='total_advertising_cost_of_sales_clicks',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='first_step_sb_ads_amz',
            name='total_return_on_advertising_spend_clicks',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='day_14_total_sales',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='total_advertising_cost_of_sales',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sb_ads_amz',
            name='total_return_on_advertising_spend',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
