# Generated by Django 5.1.3 on 2025-01-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_first_step_sb_ads_amz_day_14_total_orders_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='amazon_store',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='asin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='average_sales_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='currency_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='fba_weight_handling_fee_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='fba_weight_handling_fee_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='fba_weight_handling_fee_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='fixed_closing_fee_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='fixed_closing_fee_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='fixed_closing_fee_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='fnsku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='msku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='net_sales',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='net_units_sold',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='parent_asin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='referral_fee_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='referral_fee_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='referral_fee_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='refund_commission_fee_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='refund_commission_fee_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='refund_commission_fee_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='units_returned',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='first_step_codbfeesdata_amz',
            name='units_sold',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
