# Generated by Django 5.1.3 on 2025-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_alter_first_step_codbfeesdata_amz_amazon_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_step_sb_ads_amz',
            name='video_first_quartile_views',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
