# Generated by Django 5.1.3 on 2025-01-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_first_step_sb_ads_amz_video_first_quartile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='portfolio_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
