# Generated by Django 5.1.3 on 2025-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_alter_first_step_sp_ads_amz_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='clicks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='cpc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='ctr',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_total_orders',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='day_14_total_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='impressions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='top_of_search_impression_share',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='total_advertising_cost_of_sales',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='total_return_on_advertising_spend',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
