# Generated by Django 5.1.3 on 2025-01-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_alter_first_step_sp_ads_amz_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_sp_ads_amz',
            name='match_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
