# Generated by Django 5.1.3 on 2025-02-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_nexten_return_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexten_return_data',
            old_name='return_approved_date',
            new_name='return_approval_date',
        ),
    ]
