# Generated by Django 5.1.3 on 2025-02-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_rename_return_approved_date_nexten_return_data_return_approval_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexten_return_data',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
