# Generated by Django 5.1.3 on 2025-02-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_rename_qunatity_nexten_return_data_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexten_return_data',
            old_name='return_completion',
            new_name='return_completion_type',
        ),
    ]
