# Generated by Django 5.1.3 on 2025-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_rename_return_completion_nexten_return_data_return_completion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nexten_return_data',
            name='return_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexten_return_data',
            name='return_cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexten_return_data',
            name='return_complete_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexten_return_data',
            name='return_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexten_return_data',
            name='return_requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexten_return_data',
            name='tech_visit_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nexten_return_data',
            name='tech_visit_completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
