# Generated by Django 5.1.3 on 2025-02-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_alter_nexten_return_data_return_approval_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nexten_return_data',
            name='return_approval_date',
        ),
        migrations.RemoveField(
            model_name='nexten_return_data',
            name='return_cancellation_date',
        ),
        migrations.RemoveField(
            model_name='nexten_return_data',
            name='return_complete_by_date',
        ),
        migrations.RemoveField(
            model_name='nexten_return_data',
            name='return_completion_date',
        ),
        migrations.RemoveField(
            model_name='nexten_return_data',
            name='return_requested_date',
        ),
        migrations.RemoveField(
            model_name='nexten_return_data',
            name='tech_visit_by_date',
        ),
        migrations.RemoveField(
            model_name='nexten_return_data',
            name='tech_visit_completion_datetime',
        ),
    ]
