# Generated by Django 5.1.3 on 2025-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_remove_nexten_return_data_return_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_FK_Return_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=100)),
                ('order_item_id', models.CharField(max_length=100)),
                ('fulfilment_type', models.CharField(max_length=25)),
                ('return_status', models.CharField(max_length=100)),
                ('return_reason', models.CharField(max_length=500)),
                ('return_sub_reason', models.CharField(max_length=500)),
                ('return_type', models.CharField(max_length=100)),
                ('return_result', models.CharField(max_length=100)),
                ('return_expectation', models.CharField(max_length=100)),
                ('reverse_logistics_tracking_id', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('fsn', models.CharField(max_length=100)),
                ('product_title', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_completion_type', models.CharField(max_length=100)),
                ('primary_pv_output', models.CharField(max_length=100)),
                ('detailed_pv_output', models.CharField(max_length=100)),
                ('final_condition_of_returned_product', models.CharField(max_length=100)),
                ('tech_visit_sla', models.CharField(max_length=100)),
                ('tech_visit_completion_breach', models.CharField(max_length=100)),
                ('return_completion_sla', models.CharField(max_length=100)),
                ('return_completion_breach', models.CharField(max_length=100)),
                ('return_cancellation_reason', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'First_step_FK_Return_data',
            },
        ),
        migrations.CreateModel(
            name='Jr_Sr_FK_Return_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=100)),
                ('order_item_id', models.CharField(max_length=100)),
                ('fulfilment_type', models.CharField(max_length=25)),
                ('return_status', models.CharField(max_length=100)),
                ('return_reason', models.CharField(max_length=500)),
                ('return_sub_reason', models.CharField(max_length=500)),
                ('return_type', models.CharField(max_length=100)),
                ('return_result', models.CharField(max_length=100)),
                ('return_expectation', models.CharField(max_length=100)),
                ('reverse_logistics_tracking_id', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('fsn', models.CharField(max_length=100)),
                ('product_title', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_completion_type', models.CharField(max_length=100)),
                ('primary_pv_output', models.CharField(max_length=100)),
                ('detailed_pv_output', models.CharField(max_length=100)),
                ('final_condition_of_returned_product', models.CharField(max_length=100)),
                ('tech_visit_sla', models.CharField(max_length=100)),
                ('tech_visit_completion_breach', models.CharField(max_length=100)),
                ('return_completion_sla', models.CharField(max_length=100)),
                ('return_completion_breach', models.CharField(max_length=100)),
                ('return_cancellation_reason', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Jr_Sr_FK_Return_data',
            },
        ),
    ]
