# Generated by Django 5.1.3 on 2025-03-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_first_step_fk_return_data_jr_sr_fk_return_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_step_ReturnData_AMZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('return_request_date', models.DateField(blank=True, null=True)),
                ('return_request_status', models.CharField(max_length=25)),
                ('amazon_rma_id', models.CharField(max_length=20)),
                ('seller_rma_id', models.CharField(max_length=20)),
                ('label_type', models.CharField(max_length=30)),
                ('label_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency_code', models.CharField(max_length=5)),
                ('return_carrier', models.CharField(max_length=50)),
                ('tracking_id', models.CharField(max_length=30)),
                ('label_to_be_paid_by', models.CharField(max_length=15)),
                ('a_to_z_claim', models.CharField(max_length=3)),
                ('is_prime', models.CharField(max_length=3)),
                ('asin', models.CharField(max_length=20)),
                ('merchant_sku', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=500)),
                ('return_quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('return_reason', models.CharField(max_length=100)),
                ('in_policy', models.CharField(max_length=3)),
                ('return_type', models.CharField(max_length=20)),
                ('resolution', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=20)),
                ('return_delivery_date', models.DateField(blank=True, null=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('safet_action_reason', models.CharField(max_length=100)),
                ('safet_claim_id', models.CharField(max_length=20)),
                ('safet_claim_status', models.CharField(max_length=20)),
                ('safet_claim_creation_time', models.DateTimeField(blank=True, null=True)),
                ('safet_claim_reimbursement_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'First_step_ReturnData_AMZ',
            },
        ),
    ]
