# Generated by Django 5.1.3 on 2025-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_first_step_returndata_amz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_step_returndata_amz',
            name='label_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_returndata_amz',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_returndata_amz',
            name='order_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_returndata_amz',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_returndata_amz',
            name='return_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='first_step_returndata_amz',
            name='safet_claim_reimbursement_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
